from player import *
x = Player()
x.add_to_hand(Card("Spade", 1))
x.add_to_hand(Card("Spade", 2))
x.add_to_hand(Card("Spade", 3))
x.add_to_hand(Card("Spade", 4))
x.add_to_hand(Card("Spade", 5))
print(x.hand_value())
x.play_cards([1, 2, 3])
x.add_to_hand(Card("Spade", 6))
x.add_to_hand(Card("Spade", 7))
x.print_hand()
x.add_to_hand(Card("Spade", 8))
x.print_hand()
x.play_cards([4])
x.print_hand()
x.add_to_hand(Card("Heart", 8))
x.print_hand()
x.play_cards([1, 4])
x.print_hand()
x.play_cards([0, 2])
x.print_hand()
